# Generated by Django 3.2 on 2021-04-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
