# Generated by Django 3.2 on 2021-04-09 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_name', models.CharField(max_length=250)),
                ('video_name', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=6)),
                ('description1', models.CharField(max_length=2000)),
                ('description2', models.CharField(max_length=2000)),
                ('description3', models.CharField(max_length=2000)),
                ('avg_star_rating', models.CharField(default=0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('star', models.CharField(default=0, max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.details')),
            ],
        ),
    ]
